# Generated by Django 3.2.18 on 2023-03-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('telefone', models.CharField(max_length=11)),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
    ]
